global:
  domain: argocd.controlplane.k8s.integratn.tech
server:
  service:
    annotations:
      metallb.universe.tf/loadBalancerIPs: 10.0.4.201
      metallb.universe.tf/address-pool: default
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    tls: true

